# Page settings
title = "Funtana Apartments"
baseurl = "http://www.funtanaapartments.com/"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Funtana Apartments"
    home = "Home"
    apartments = "Our apartments"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Funtana Apartments"
    subtitle = 'Enjoy your vacation'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Big Apartment"
    description = "The big apartment (100 m2) is located on the first floor and can accommodate up to 6 people. The apartment consists of a big living room with kitchen and 2 bedrooms. Top tip: Terrace is the perfect place to enjoy your morning coffee ;)"
    url = "/apartment/top"
    button = "Details"
    icon = "icon-arrow-up-circle"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Small Apartment"
    description = "The small apartment (55m2) is located on the ground floor to the left and can accommodate up to 4 people. The apartment has a big living room with kitchen and 1 bedroom. Top tip: The couch is the perfect place to rest up until your next adventure ;)"
    url = "/apartment/left"
    button = "Details"
    icon = "icon-arrow-left-circle"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Studio Apartment"
    description = "Studio apartment (45m2) is located on the ground floor to the right and can accommodate up to 3 people. It has a big living room with kitchen and a comfy bed. Top tip: Jump into the bed after a perfect Istrian lunch and watch TV ;)"
    url = "/apartment/right"
    button = "Details"
    icon = "icon-arrow-right-circle"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Funtana"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=LFo3lq6ImDg"


  # Apartments section
  [params.apartments]
    title = "Our Apartments"
    description = "Our apartments are located in a brand new two story house built in 2017 which consists of 3 apartments. You can choose between the studio and the small apartment on the ground floor and the big apartment on the first floor. All apartments have parking space, air conditioning and free WIFI."
 
  # Contact section
  [params.contact]
    map = true
    title = "Get in touch"
    description = "Interested in booking an apartment or just looking for more information? Do not hesitate to drop us a line!"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Dalmatinska 11k, <br> Funtana, Croatia"],
        ["icon-phone", "+385 91 554 7733"],
        ["icon-envelope", "funtanaapartments@googlegroups.com"],
        ["icon-globe", '<a href="http://www.funtanaapartments.com" target="_blank">funtanaapartments.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    copyright = '&copy; 2017 funtanaapartments.com'
