# Page settings
title = "Funtana Apartments"
baseurl = "http://www.funtanaapartments.com/"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Funtana Apartments"
    home = "Home"
    apartments = "Our apartments"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Funtana Apartments"
    subtitle = 'Enjoy your vacation'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Top Apartment"
    description = "Upper apartment has 100 square meters. somem mdodmf sakfjsf salkflk  aflsalfk amlsdlk akdf kaflsk asf "
    url = "/apartment/top"
    button = "Details"
    icon = "icon-arrow-up-circle"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Left Apartment"
    description = "Left apartment has 2 bedrooms. asmd ekfj fjwefjkkjfjkgj 3rjg jvmldls ljklkf lslfk slkklflks fkslkfj lsnl"
    url = "/apartment/left"
    button = "Details"
    icon = "icon-arrow-left-circle"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Right Apartment"
    description = "Right apartment is a single room. sf sjdf jksdkjfk j3jkrfijk 3n n37jk 3kj jf 3fmn3krjfi jk3rj 3k jk4"
    url = "/apartment/right"
    button = "Details"
    icon = "icon-arrow-right-circle"
    img = "img_10.jpg"

  [params.intro.video]
    enable = false
    title = "Funtana"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=LFo3lq6ImDg"


  # Apartments section
  [params.apartments]
    title = "Our Apartments"
    description = "Our apartments are located in a 2 story house build in 2017. House consists of total 3 apartments. You can choose between two smaller apartments on ground floor and a big apartment at first story."
 
  # Contact section
  [params.contact]
    map = true
    title = "Get in touch"
    description = "Interested in booking an apartment or just looking for more information? Do not hesitate to drop us a line!"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "Dalmatinska 11k, <br> Funtana, Croatia"],
        ["icon-phone", "+385 91 554 7733"],
        ["icon-envelope", "funtanaapartments@googlegroups.com"],
        ["icon-globe", '<a href="http://www.funtanaapartments.com" target="_blank">funtanaapartments.com</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    copyright = '&copy; 2017 funtanaapartments.com'
